# Generated by Django 5.0.6 on 2024-07-08 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kunci_transaksi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kuncitransaksi',
            table='kunci_transaksi',
        ),
    ]
