# Generated by Django 5.0.6 on 2024-07-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kunci_transaksi', '0002_alter_kuncitransaksi_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='kuncitransaksi',
            name='jenis_transaksi',
            field=models.CharField(choices=[('kas', 'kas'), ('bank memorial', 'Bank Memorial')], default='', max_length=13),
            preserve_default=False,
        ),
    ]
