# Generated by Django 5.0.6 on 2024-07-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('alamat', models.TextField(null=True)),
                ('no_hp', models.CharField(max_length=15, unique=True)),
                ('piutang', models.DecimalField(decimal_places=2, max_digits=13)),
            ],
        ),
    ]
