# Generated by Django 5.0.6 on 2024-07-11 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kode_akun', '0003_alter_kodeakun_kode_induk'),
        ('memorial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorial',
            name='kode_akun',
        ),
        migrations.AlterField(
            model_name='memorialdetail',
            name='kode_lawan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorial_details_as_kode_akun', to='kode_akun.kodeakun'),
        ),
    ]
