# Generated by Django 5.0.6 on 2024-07-11 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kode_akun', '0003_alter_kodeakun_kode_induk'),
        ('memorial', '0002_remove_memorial_kode_akun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorialdetail',
            name='kode',
            field=models.ForeignKey(default='', help_text='kode_akun', on_delete=django.db.models.deletion.CASCADE, related_name='memorial_details_as_kode', to='kode_akun.kodeakun'),
            preserve_default=False,
        ),
    ]
