# Generated by Django 5.0.6 on 2024-07-11 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kode_akun', '0003_alter_kodeakun_kode_induk'),
        ('memorial', '0004_rename_kode_memorialdetail_kode_akun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorialdetail',
            name='kode_akun',
            field=models.ForeignKey(help_text='kode_akun', on_delete=django.db.models.deletion.CASCADE, related_name='memorial_details_as_kode_akun', to='kode_akun.kodeakun'),
        ),
        migrations.AlterField(
            model_name='memorialdetail',
            name='kode_lawan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorial_details_as_kode_lawan', to='kode_akun.kodeakun'),
        ),
    ]
