# Generated by Django 5.0.6 on 2024-07-09 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kode_akun', '0003_alter_kodeakun_kode_induk'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaksiKas',
            fields=[
                ('kode_transaksi', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('tipe', models.CharField(choices=[('masuk', 'Masuk'), ('keluar', 'Keluar')], max_length=6)),
                ('total', models.DecimalField(decimal_places=2, max_digits=13)),
                ('kode_akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kode_akun.kodeakun')),
            ],
            options={
                'db_table': 'transaksi_kas',
            },
        ),
        migrations.CreateModel(
            name='TransaksiKasDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=13)),
                ('keterangan', models.TextField(null=True)),
                ('kode_lawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kode_akun.kodeakun')),
                ('kode_transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaksi_kas.transaksikas')),
            ],
            options={
                'db_table': 'transaksi_kas_detail',
            },
        ),
    ]
