# Generated by Django 5.0.6 on 2024-07-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurnal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('kode_transaksi', models.CharField(max_length=20)),
                ('jenis_transaksi', models.CharField(choices=[('kas', 'Kas'), ('bank', 'Bank'), ('memorial', 'Memorial')], max_length=8)),
                ('tipe', models.CharField(choices=[('debit', 'Debit'), ('kredit', 'Kredit')], max_length=6)),
                ('kode_akun', models.CharField(max_length=15)),
                ('kode_lawan', models.CharField(max_length=15)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=13)),
                ('keterangan', models.TextField(null=True)),
                ('id_transaksi', models.BigIntegerField(max_length=20)),
            ],
            options={
                'db_table': 'jurnal',
            },
        ),
    ]
