# Generated by Django 5.0.6 on 2024-07-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurnal',
            name='id_transaksi',
            field=models.BigIntegerField(),
        ),
    ]
