# Generated by Django 5.0.6 on 2024-07-09 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_authuserhasrole'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthUserHasRole',
        ),
    ]
