# Generated by Django 5.0.6 on 2024-07-09 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('transaksi', 'Transaksi'), ('sistem', 'Sistem')], max_length=10)),
                ('keterangan', models.TextField(null=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'log_activity',
            },
        ),
        migrations.CreateModel(
            name='LogActivityDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_transaksi', models.CharField(choices=[('kas', 'Kas'), ('bank', 'Bank'), ('memorial', 'Memorial')], max_length=8)),
                ('tipe', models.CharField(choices=[('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete')], max_length=8)),
                ('keterangan', models.TextField()),
                ('id_log_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log_activity.logactivity')),
            ],
            options={
                'db_table': 'log_activity_detail',
            },
        ),
    ]
