# Generated by Django 5.0.6 on 2024-07-10 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_activity', '0002_logactivity_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logactivity',
            old_name='id_user',
            new_name='user_id',
        ),
    ]
