# Generated by Django 5.0.6 on 2024-07-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_activity', '0004_remove_logactivity_user_id_logactivity_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logactivity',
            name='kategori',
            field=models.CharField(choices=[('master', 'Master'), ('transaksi', 'Transaksi'), ('sistem', 'Sistem')], max_length=10),
        ),
    ]
