# Generated by Django 5.0.6 on 2024-07-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KodeInduk',
            fields=[
                ('kode_induk', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
            ],
        ),
    ]
