# Generated by Django 5.0.6 on 2024-07-17 03:39

from django.db import migrations


class Migration(migrations.Migration):
    initial = True
    
    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE VIEW view_laba_rugi AS
            SELECT 
                MONTH(tanggal) AS bulan,
                YEAR(tanggal) AS tahun,
                SUM(nominal) AS nominal,
                kode_akun,
                kode_lawan,
                tipe
            FROM 
                jurnal
            WHERE 
                kode_akun LIKE '4%' OR 
                kode_akun LIKE '5%' OR 
                kode_akun LIKE '6%' OR 
                kode_lawan LIKE '4%' OR 
                kode_lawan LIKE '5%' OR 
                kode_lawan LIKE '6%'
            GROUP BY 
                MONTH(tanggal), 
                YEAR(tanggal), 
                kode_akun, 
                kode_lawan, 
                tipe
            ORDER BY 
                MONTH(tanggal), 
                YEAR(tanggal);
            """,
            reverse_sql="DROP VIEW IF EXISTS view_laba_rugi;"
        ),
    ]
