# Generated by Django 5.0.6 on 2024-07-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buku_besar', '0001_create_view_laba_rugi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewLabaRugi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.IntegerField()),
                ('tahun', models.IntegerField()),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('kode_akun', models.CharField(max_length=255)),
                ('kode_lawan', models.CharField(max_length=255)),
                ('tipe', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'view_laba_rugi',
                'managed': False,
            },
        ),
    ]
