# Generated by Django 5.0.6 on 2024-07-08 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kode_induk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KodeAkun',
            fields=[
                ('kode_akun', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('tipe', models.CharField(choices=[('debit', 'Debit'), ('kredit', 'Kredit')], max_length=6)),
                ('kode_induk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kode_akun_kode_induk_foreign', to='kode_induk.kodeinduk')),
            ],
        ),
    ]
