# Generated by Django 5.0.6 on 2024-07-08 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kode_akun', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kodeakun',
            table='kode_akun',
        ),
    ]
