# Generated by Django 5.0.6 on 2024-07-08 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kode_akun', '0002_alter_kodeakun_table'),
        ('kode_induk', '0002_alter_kodeinduk_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kodeakun',
            name='kode_induk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kode_induk.kodeinduk'),
        ),
    ]
